{% set name = "typing_inspect" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 811b44f92e780b90cfe7bac94249a4fae87cfaa9b40312765489255045231d9c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - typing >=3.6.1 # [py<35]
    - mypy_extensions >=0.3.0
    - typing_extensions >=3.7.4

test:
  imports:
    - typing_inspect

about:
  home: http://github.com/ilevkivskyi/typing_inspect
  license: MIT
  license_file: LICENSE
  summary: 'The “typing_inspect” module defines experimental API for runtime inspection of types defined in the standard “typing” module.'

extra:
  recipe-maintainers:
    - tarcisioe
