travis:
  secure:
    BINSTAR_TOKEN: WpFh7RFNeOGR442QJQsRoNHodOxsyUY9ASK7/2m0g9N4UA/huIQJ7VhxI2P+4TMZXPo8QbmMG5P2x4Ut49aH5iq0PS4zaQcN8fTPMpyA9UdQo/9yGPqHfYCwE+8DpUwwjCtnXQDhmJvDbdUkk9KUIAOCMsnb6LjRba9K332EwMKWKaNns4+1WxLdaqyiUZkBe9piRYqjNgF/gflELPghZu4fK+umX9p+gi5mMIF9jBPz0ZsBZ6C2Tmo5kwU5so3cUI55qrw4rwZq768/heHOKDHbvDdiDLLUh1zl3/muqiA6NAbghzrEvEyxI0PY0Zc/qQ83WCKfx4H8NkLqVfdTvVVqtQ2CXV5MkvM+iPGTItKfiv/E2YAOtnuU30VQoY5nOm9n+fzuAy/SXVxE9ZHyjGshAxAsn6rXOeypSd5y2VjaONugdZMkQzQ0LFEZ7ckDGaL5+atyOqo8Ul9Z8PwvThmhv/SGikFW0I2bLxgKsDlTo9hIdeOAiBBqhK81N7tF3noTfBH15mYBQZ71dnpZVA37E8quvZGZm2rviN1sq8ZQ2yhkWfkIuq4utEwsctsOj9/wVTRmJ1sTPKH6Cr209HPGTnUfde0rkTp+uqpuXeXc0FCy/4o9BAT4tHsL5chQPOxJ70JRDZuoSQuscAsFqdrVQ/9ebXGX03sMjWiQagM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
